// F7.2: all user-facing copy lives here, even at single-locale MVP, so a
// future locale is a new file in this shape rather than a hunt through every
// component. Voice rules (no em dashes, no identity language) live in
// specs/05-ui-styleguide.md and apply to every string below.
export const strings = {
  common: {
    loading: "Loading...",
    logIn: "Log in",
    logInPrompt: "Log in to continue.",
    cancel: "Cancel",
  },
  nav: {
    feed: "Feed",
    post: "Post",
    notifications: "Notifications",
    profile: "Profile",
    newPost: "New post",
    anonymousSession: "Anonymous session",
  },
  home: {
    tagline:
      "Post anonymously. Every image becomes a cartoon before anyone sees it. No names, no location, ever.",
    createAccount: "Create account",
    viewFeed: "View feed",
    newPost: "New post",
    blockedHandles: "Blocked handles",
    moderationActions: "Moderation actions",
    moderationQueue: "Moderation queue",
    complianceFlags: "Compliance flags",
    rerollHandle: "Reroll handle",
    logOut: "Log out",
    deleteAccount: "Delete account",
    deleteConfirmBody: "This permanently deletes your account and posts. This cannot be undone.",
    deleteConfirmYes: "Yes, delete",
    follower: (count: number) => `${count} follower${count === 1 ? "" : "s"}`,
    reroll: (count: number) => `${count} handle reroll${count === 1 ? "" : "s"} left`,
  },
  rightRail: {
    title: "Non-negotiable",
    pillars: [
      {
        title: "Always cartoonized",
        body: "No path exists for a real photo to reach storage or the feed.",
      },
      {
        title: "No location, ever",
        body: "Nothing is geotagged, ranked, or grouped by region.",
      },
      {
        title: "No algorithm",
        body: "Chronological or shuffled global. Never personalized.",
      },
    ],
  },
  feed: {
    title: "Toonymous",
    recent: "Recent",
    shuffle: "Shuffle",
    empty: "No posts yet. Be the first.",
    noAlgorithm: "No \"for you\" feed",
    loadMore: "Load more",
    loadMoreBusy: "Loading...",
    loadError: "could not load the feed",
  },
  postCard: {
    imageAlt: "Cartoonized post",
    liked: "Liked",
    like: "Like",
    following: "Following",
    follow: "Follow",
    comments: "Comments",
    report: "Report",
    block: "Block",
    moreActions: "More actions",
    cartoonizedBadge: "Cartoonized",
    likesLabel: "likes",
    viewComments: (count: number) => `View all ${count} comment${count === 1 ? "" : "s"}`,
    blockConfirm: (handle: string) => `Block ${handle}? You will no longer see their posts.`,
    blockConfirmYes: "Yes, block",
    reportPrompt: "Why are you reporting this post?",
    reportPlaceholder: "Tell moderators what's wrong with this post",
    reportSubmit: "Send report",
    reportSent: "Report sent to moderators.",
    reportError: "could not send report",
    blockError: "could not block",
    followError: "could not update follow status",
  },
  compose: {
    title: "New post",
    dropzoneLabel: "Drop a photo, or click to choose one",
    dropzoneHint: "Converted to a cartoon instantly. The original is never stored.",
    safetyNote:
      "Your photo is processed only long enough to generate the cartoon. Toonymous never stores, displays, or can recover the original, for you or anyone else.",
    captionLabel: "Caption (optional)",
    submit: "Post",
    submitting: "Posting...",
    viewFeed: "View feed",
    tryAgain: "Try again",
    genericError: "could not post, please try again",
    status: {
      pending: "Cartoonizing your post...",
      ready: "Posted.",
      blocked: "This image did not pass the safety check and was not posted.",
      failed: "Something went wrong converting this image. It was not posted.",
    },
  },
  postDetail: {
    noComments: "No comments yet.",
    commentPlaceholder: "Add a comment",
    submit: "Post",
    loginToComment: "Log in to comment.",
    loadError: "could not load this post",
    commentError: "could not post comment",
  },
  blocked: {
    title: "Blocked handles",
    inputPlaceholder: "handle to block",
    block: "Block",
    unblock: "Unblock",
    empty: "No blocked handles.",
    loginPrompt: "Log in to manage blocked handles.",
    loadError: "could not load blocked handles",
    blockError: "could not block that handle",
    unblockError: "could not unblock that handle",
  },
  appeals: {
    title: "Moderation actions",
    empty: "No moderation actions on your account.",
    loginPrompt: "Log in to view moderation actions on your account.",
    appeal: "Appeal",
    appealPrompt: "Why should this be reversed?",
    appealPlaceholder: "Explain why this action should be reversed",
    appealSubmit: "Send appeal",
    appealPending: (status: string) => `Appeal ${status}`,
    appealError: "could not submit appeal",
    loadError: "could not load",
    actions: {
      remove_content: "Content removed",
      shadow_limit: "Account shadow-limited",
      ban: "Account banned",
    } as Record<string, string>,
  },
  login: {
    title: "Welcome back",
    submit: "Log in",
    submitting: "Logging in...",
    error: "login failed, please try again",
    signupPrompt: "New here?",
    signupLink: "Create an account",
  },
  signup: {
    title: "Join Toonymous",
    subtitle: "You will get a random handle. No name, no location, ever.",
    submit: "Create account",
    submitting: "Creating account...",
    error: "signup failed, please try again",
    loginPrompt: "Already have an account?",
    loginLink: "Log in",
  },
} as const;
