// F7.2: all user-facing copy lives here, even at single-locale MVP, so a
// future locale is a new file in this shape rather than a hunt through every
// component. Voice rules (no em dashes, no identity language) live in
// specs/05-ui-styleguide.md and apply to every string below.
export const strings = {
  common: {
    loading: "Loading...",
    logIn: "Log in",
    logInPrompt: "Log in to continue.",
    cancel: "Cancel",
    close: "Close",
    back: "Go back",
    dismiss: "Dismiss",
    retry: "Try again",
    notAuthorized: "You do not have access to this page.",
    somethingWrong: "Something went wrong.",
  },
  nav: {
    feed: "Feed",
    post: "Post",
    notifications: "Notifications",
    profile: "Profile",
    newPost: "New post",
    anonymousSession: "Anonymous session",
    appearance: "Accent theme",
  },
  home: {
    tagline:
      "Post anonymously. Every image becomes a cartoon before anyone sees it. No names, no location, ever.",
    createAccount: "Create account",
    viewFeed: "View feed",
    newPost: "New post",
    blockedHandles: "Blocked handles",
    blockedHandlesHint: "Handles you have hidden from your feed",
    moderationActions: "Moderation actions",
    moderationActionsHint: "Anything moderators have done to your account",
    moderationQueue: "Moderation queue",
    moderationQueueHint: "Open reports and pending appeals",
    complianceFlags: "Compliance flags",
    complianceFlagsHint: "Unreviewed safety pre-check matches",
    rerollHandle: "Reroll handle",
    rerollHandleHint: "Get a new randomly generated handle",
    rerollNoneLeft: "No rerolls left on this account",
    rerollSuccess: "New handle assigned.",
    logOut: "Log out",
    loggedOut: "Logged out.",
    deleteAccount: "Delete account",
    deleteConfirmTitle: "Delete your account?",
    deleteConfirmBody: "This permanently deletes your account and posts. This cannot be undone.",
    deleteConfirmYes: "Yes, delete",
    accountSection: "Your account",
    staffSection: "Staff tools",
    appearanceSection: "Appearance",
    appearanceHint: "Pick the accent palette used across the app. Saved on this device.",
    dangerSection: "Account actions",
    follower: (count: number) => `${count} follower${count === 1 ? "" : "s"}`,
    reroll: (count: number) => `${count} handle reroll${count === 1 ? "" : "s"} left`,
    followersLabel: "Followers",
    rerollsLabel: "Rerolls left",
    landing: {
      headline: "Anonymous by design.",
      headlineAccent: "Cartoon by default.",
      pillarsTitle: "How it works",
      steps: [
        {
          title: "Sign up with an email only",
          body: "You get a randomly generated handle and an abstract avatar. No name, no phone, no profile to fill in.",
        },
        {
          title: "Every photo becomes a cartoon",
          body: "Images are converted on upload. The original is never stored and cannot be recovered by anyone.",
        },
        {
          title: "One global feed, no ranking",
          body: "Newest first or shuffled. Nothing is personalized, geotagged, or grouped by region.",
        },
      ],
    },
  },
  rightRail: {
    title: "Non-negotiable",
    pillars: [
      {
        title: "Always cartoonized",
        body: "No path exists for a real photo to reach storage or the feed.",
      },
      {
        title: "No location, ever",
        body: "Nothing is geotagged, ranked, or grouped by region.",
      },
      {
        title: "No algorithm",
        body: "Chronological or shuffled global. Never personalized.",
      },
    ],
  },
  feed: {
    title: "Toonymous",
    subtitle: "One global feed. Newest first, or shuffled.",
    recent: "Recent",
    shuffle: "Shuffle",
    tabsLabel: "Feed order",
    empty: "No posts yet. Be the first.",
    emptyTitle: "Nothing here yet",
    emptyAction: "Create the first post",
    noAlgorithm: "No \"for you\" feed",
    loadMore: "Load more",
    loadMoreBusy: "Loading...",
    loadError: "could not load the feed",
    errorTitle: "Could not load the feed",
    loadingLabel: "Loading posts",
    endOfFeed: "You have reached the end.",
  },
  postCard: {
    imageAlt: "Cartoonized post",
    liked: "Liked",
    like: "Like",
    following: "Following",
    follow: "Follow",
    unfollowed: "Unfollowed.",
    followed: "Following this handle.",
    comments: "Comments",
    report: "Report",
    block: "Block",
    moreActions: "More actions",
    cartoonizedBadge: "Cartoonized",
    likesLabel: "likes",
    viewComments: (count: number) => `View all ${count} comment${count === 1 ? "" : "s"}`,
    blockConfirmTitle: "Block this handle?",
    blockConfirm: (handle: string) => `Block ${handle}? You will no longer see their posts.`,
    blockConfirmYes: "Yes, block",
    blockedToast: "Handle blocked. Their posts are hidden from you.",
    reportTitle: "Report this post",
    reportPrompt: "Why are you reporting this post?",
    reportPlaceholder: "Tell moderators what's wrong with this post",
    reportSubmit: "Send report",
    reportSent: "Report sent to moderators.",
    reportError: "could not send report",
    blockError: "could not block",
    followError: "could not update follow status",
    pendingLabel: "Still cartoonizing",
  },
  compose: {
    title: "New post",
    subtitle: "Your photo becomes a cartoon before anyone, including us, can see it.",
    dropzoneLabel: "Drop a photo, or click to choose one",
    dropzoneHint: "Converted to a cartoon instantly. The original is never stored.",
    dropzoneActive: "Release to add this photo",
    previewAlt: "Photo you selected, shown only on this device",
    changePhoto: "Change photo",
    removePhoto: "Remove photo",
    safetyNote:
      "Your photo is processed only long enough to generate the cartoon. Toonymous never stores, displays, or can recover the original, for you or anyone else.",
    styleLabel: "Cartoon style",
    styles: {
      anime: { label: "Anime", hint: "Best for faces" },
      sketch: { label: "Sketch", hint: "Pencil drawing" },
      comic: { label: "Comic", hint: "Bold colors, inked edges" },
    },
    captionLabel: "Caption (optional)",
    captionHint: "Personal details are scrubbed automatically before posting.",
    submit: "Post",
    submitting: "Posting...",
    viewFeed: "View feed",
    tryAgain: "Try again",
    genericError: "could not post, please try again",
    statusTitle: {
      pending: "Cartoonizing",
      ready: "Posted",
      blocked: "Not posted",
      failed: "Not posted",
    },
    status: {
      pending: "Cartoonizing your post...",
      ready: "Posted.",
      blocked: "This image did not pass the safety check and was not posted.",
      failed: "Something went wrong converting this image. It was not posted.",
    },
    pendingHint: "This usually takes a few seconds. You can stay on this screen.",
    readyHint: "Your cartoon is live in the global feed.",
  },
  postDetail: {
    title: "Post",
    commentsTitle: (count: number) => `${count} comment${count === 1 ? "" : "s"}`,
    noComments: "No comments yet.",
    noCommentsBody: "Be the first to say something.",
    commentPlaceholder: "Add a comment",
    commentLabel: "Your comment",
    submit: "Post",
    loginToComment: "Log in to comment.",
    loadError: "could not load this post",
    errorTitle: "Could not load this post",
    commentError: "could not post comment",
    commentSent: "Comment posted.",
  },
  blocked: {
    title: "Blocked handles",
    subtitle: "Posts and comments from these handles stay hidden from you.",
    inputLabel: "Handle to block",
    inputPlaceholder: "handle to block",
    block: "Block",
    unblock: "Unblock",
    empty: "No blocked handles.",
    emptyBody: "Handles you block from a post's menu show up here.",
    loginPrompt: "Log in to manage blocked handles.",
    loadError: "could not load blocked handles",
    blockError: "could not block that handle",
    unblockError: "could not unblock that handle",
    blockedToast: "Handle blocked.",
    unblockedToast: "Handle unblocked.",
  },
  appeals: {
    title: "Moderation actions",
    subtitle: "Anything moderators have done to your account or content, and the appeals you filed.",
    empty: "No moderation actions on your account.",
    emptyBody: "Nothing has been removed, limited, or banned.",
    loginPrompt: "Log in to view moderation actions on your account.",
    appeal: "Appeal",
    appealTitle: "Appeal this action",
    appealPrompt: "Why should this be reversed?",
    appealPlaceholder: "Explain why this action should be reversed",
    appealSubmit: "Send appeal",
    appealSent: "Appeal sent. A moderator will review it.",
    appealPending: (status: string) => `Appeal ${status}`,
    appealError: "could not submit appeal",
    loadError: "could not load",
    loadingLabel: "Loading moderation actions",
    actions: {
      remove_content: "Content removed",
      shadow_limit: "Account shadow-limited",
      ban: "Account banned",
    } as Record<string, string>,
  },
  moderation: {
    title: "Moderation queue",
    subtitle: "Open reports and pending appeals, oldest first.",
    tabsLabel: "Queue",
    reports: "Reports",
    appeals: "Appeals",
    loadError: "could not load queue",
    resolveError: "could not resolve report",
    appealError: "could not resolve appeal",
    reportedBy: (type: string, author: string, reporter: string) =>
      `${type} by ${author}, reported by ${reporter}`,
    unknownAuthor: "unknown",
    reasonLabel: "Reason",
    noReports: "No open reports.",
    noReportsBody: "The report queue is clear.",
    noAppeals: "No pending appeals.",
    noAppealsBody: "Every appeal has been reviewed.",
    appealContext: (handle: string, action: string, target: string) =>
      `${handle} is appealing ${action} on a ${target}`,
    resolved: "Report resolved.",
    appealResolved: "Appeal resolved.",
    actions: {
      no_action: "No action",
      remove_content: "Remove content",
      shadow_limit: "Shadow-limit",
      ban: "Ban",
      approve: "Approve",
      deny: "Deny",
    },
  },
  compliance: {
    title: "Compliance flags",
    subtitle:
      "Automated safety pre-check matches, unreviewed. No image content is stored or shown here, the original was never written to disk.",
    markReviewed: "Mark reviewed",
    reviewed: "Flag marked reviewed.",
    empty: "No unreviewed flags.",
    emptyBody: "Nothing is waiting on compliance review.",
    loadError: "could not load",
    reviewError: "could not mark reviewed",
  },
  login: {
    title: "Welcome back",
    subtitle: "Log in to your anonymous handle.",
    submit: "Log in",
    submitting: "Logging in...",
    error: "login failed, please try again",
    signupPrompt: "New here?",
    signupLink: "Create an account",
  },
  signup: {
    title: "Join Toonymous",
    subtitle: "You will get a random handle. No name, no location, ever.",
    passwordHint: "At least 8 characters.",
    submit: "Create account",
    submitting: "Creating account...",
    error: "signup failed, please try again",
    loginPrompt: "Already have an account?",
    loginLink: "Log in",
  },
} as const;
